ascii_art = r"""

                                         .  .  .;dxxxxxxxxo,.     ..................................
                                              .cxkkkkkkxxo'             ............................
                 . .'''..                    .lkkkkkkkkkl.              ............................
             ..    'oddl.                  .,dkkkkkkkkkl.             .... .';'.....................
          .  ...';:ldddl.                 .;xOOOOOOOOOOo.         .....  . .:ddl:'..................
         ..,;coxkkkxxdl;.                .ckOOOOOOOOOOOOl.     . .....     .:dxxxxoc,...............
    ..';coxkOOOkxoc;'..                 .lOOOOOOOOOOOOOOOc.     . ....      ..;cdxkkkxl:'...........
   'ldkkOOOkdl:,..                     'dOOOOOOOOOOOOOOOOk:.    . ...           .,cdkOOOkoc,........
   ;xkkOOkl'.                        .;xOOOOOO0kodOO0OOOOOx,      .. ..            .'cdkOOOkdc,.....
   .:oxOOOkdc,.                     .:kOOO0OO0k:..cd0OOOOOOd'    ........              .:okOOkkd;. .
      .;lxOOOOxl;..                .lkOOOOOOOx;    ,x0O0OOOOo.   ..........           .';lxOkkkk:.  
         .,lxkOOkxo:'..           'okOOOOOOOd'      :k0OOOOOOc.     .   ...... ...,:coxOOOOkxoc;.   
            .':oxkkxdo:'.       .,dkkOOOOOOo.       .cOOOOOOOk:.     ..  ....,;codkkOOkxoc;'.       
                .;codddc.      .:xkkkOOOOkl.         .oOOOOOkOx;     .  .  .:dxxxxdoc;'.            
                   .,:oc.     .cxkkkkkkOx:.           'dOOOkkkkd'     .    .:dddc'.                 
                      ..     .lxxkkkkkkd;              ,xOkkkkkko.    .    .;llc.                ...
                            'oxxxxxkkko'                :xkkkkkkxc.  ..                       ......
                          .,odxxxxxxxl.                 .ckkkxxxxx:.                    ............
                         .:ddddxxxxdc.                   .lkxxxxxxdc;;;;;;;,.         ..............
                        .cdddddddxd;.                     .oxxxxxddxxdxxxdxl.      .................
                       'lddddddddo,                        ,dxddddddddddddxl.      .................
                      .lddddddddl'                          ;odddddddddddddc.      .................
        """
